# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-25 22:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learning',
            name='question_day',
            field=models.IntegerField(default=1),
        ),
    ]
