# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-25 21:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_reg_app', '0002_auto_20161021_1121'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='question_on',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='user',
            name='stars',
            field=models.IntegerField(default=0),
        ),
    ]
